# shellcheck shell=bash
# Shared installer helpers. Dry runs only print plans, including file contents.

fail() { echo "$*" >&2; exit 1; }

validate_options() {
  if [[ -n "$ROOT_PREFIX" ]]; then
    (( DRY_RUN )) || fail '--root is only allowed with --dry-run (tests only).'
    [[ "$ROOT_PREFIX" == /* && "$ROOT_PREFIX" != / ]] || fail '--root needs an absolute fake root, not /.'
    ROOT_PREFIX="$(realpath -m -- "$ROOT_PREFIX")"
    [[ "$ROOT_PREFIX" != / ]] || fail '--root must not resolve to /.'
  fi
  (( ! PURGE || REMOVE )) || fail '--purge requires --remove.'
}

path_at_root() { printf '%s%s' "$ROOT_PREFIX" "$1"; }

run() {
  if (( DRY_RUN )); then
    printf 'PLAN '; printf '%q ' "$@"; printf '\n'
  else
    "$@"
  fi
}

directory() { run install -d -m "$2" -o root -g root -- "$(path_at_root "$1")"; }

write_file() {
  local path mode contents temporary
  path="$(path_at_root "$1")" mode="$2" contents="$3"
  if (( DRY_RUN )); then
    printf 'WRITE %s mode=%s owner=root:root\n%s\n' "$path" "$mode" "$contents"
  else
    temporary="$(mktemp "$path.tmp.XXXXXX")"
    printf '%s\n' "$contents" > "$temporary"
    chmod "$mode" "$temporary"
    chown root:root "$temporary"
    mv -f -- "$temporary" "$path"
  fi
}

preflight() {
  if (( ! DRY_RUN )); then
    [[ $EUID -eq 0 ]] || fail 'Run as root (sudo).'
    require_root_owned_tree "$REPO"
  fi
}

require_node() {
  NODE="$(command -v node || true)"
  [[ -n "$NODE" ]] || fail 'Node.js 22 or newer is required.'
  if (( ! DRY_RUN )); then
    require_trusted_binary "$NODE"
    (( $("$NODE" -p 'process.versions.node.split(".")[0]') >= 22 )) || fail 'Node.js 22 or newer is required.'
  fi
}

install_group() {
  if (( DRY_RUN )) || ! getent group wayroost >/dev/null; then
    run groupadd --system wayroost
  fi
}

install_build() {
  local kind="$1" dest="$2" npm
  if (( ! DRY_RUN )); then
    [[ -f "$REPO/dist/$kind/$3" ]] || fail "Build first: npm run build:$kind (and build:web for the server)."
    [[ "$kind" != server || -f "$REPO/dist/web/index.html" ]] || fail 'Build the web assets first: npm run build:web.'
  fi
  npm="$(command -v npm || true)"
  [[ -n "$npm" ]] || fail 'npm is required.'
  if (( ! DRY_RUN )); then require_trusted_binary "$npm"; fi
  directory /opt/wayroost 0755
  directory "$dest" 0755
  directory "$dest/dist" 0755
  run rsync -a --delete -- "$REPO/dist/$kind" "$(path_at_root "$dest")/dist/"
  if [[ "$kind" == server ]]; then
    run rsync -a --delete -- "$REPO/dist/web" "$(path_at_root "$dest")/dist/"
  fi
  run install -m 0644 -o root -g root -- "$REPO/package.json" "$REPO/package-lock.json" "$(path_at_root "$dest")/"
  run env NPM_CONFIG_USERCONFIG=/dev/null NPM_CONFIG_GLOBALCONFIG=/dev/null NPM_CONFIG_CACHE="$(path_at_root "$dest")/.npm-cache" \
    "$npm" ci --prefix "$(path_at_root "$dest")" --omit=dev --ignore-scripts --no-audit --no-fund
  run rm -rf -- "$(path_at_root "$dest")/.npm-cache"
  run chown -R root:root -- "$(path_at_root "$dest")"
  run chmod -R a+rX,go-w -- "$(path_at_root "$dest")"
}

install_unit() {
  local contents
  contents="${2:-$(cat "$REPO/deploy/$1.service")}"
  contents="${contents//\/usr\/bin\/node/$NODE}"
  directory /etc/systemd/system 0755
  write_file "/etc/systemd/system/$1.service" 0644 "$contents"
}

remove_unit() {
  # Fail if stopping fails; never erase a service's files while it is running.
  if (( DRY_RUN )) || [[ -f "/etc/systemd/system/$1.service" ]]; then
    run systemctl disable --now "$1.service"
  fi
  run rm -f -- "$(path_at_root "/etc/systemd/system/$1.service")"
  run systemctl daemon-reload
  run systemctl reset-failed "$1.service" || true
}

remove_shared_directories() {
  if (( DRY_RUN )); then
    printf 'PLAN rmdir %s %s (only if empty)\n' "$(path_at_root /opt/wayroost)" "$(path_at_root /etc/wayroost)"
    printf 'PLAN groupdel wayroost (only if neither Wayroost unit remains and the group has no members)\n'
  else
    rmdir /opt/wayroost /etc/wayroost 2>/dev/null || true
    if [[ ! -f /etc/systemd/system/wayroost-server.service && ! -f /etc/systemd/system/wayroost-supervisor.service ]]; then
      local members
      members="$(getent group wayroost | cut -d: -f4)" || return 0
      if [[ -z "$members" ]]; then groupdel wayroost; fi
    fi
  fi
}

require_supervisor_tls() {
  if (( ! DRY_RUN )); then
    [[ -s "$(path_at_root /etc/wayroost/supervisor-tls-cert.pem)" ]] || fail 'Missing supervisor TLS certificate; re-run install-supervisor.sh before installing the server.'
  fi
}

# Private material is generated by the root-owned tool, never by write_file (which prints plans).
install_tls() {
  local service="$1" tool="$2"
  if (( DRY_RUN )); then
    echo "KEEP or GENERATE $service TLS certificate: ECDSA P-256, 3650 days, SAN 127.0.0.1 and localhost"
    echo "TLS private key $(path_at_root /etc/wayroost)/$service-tls-key.pem mode=0600 owner=root:root (never printed)"
    echo "TLS certificate $(path_at_root /etc/wayroost)/$service-tls-cert.pem mode=0644 owner=root:root"
    echo 'TLS keys delivered only via systemd LoadCredential; only public SHA-256 SPKI fingerprints may be printed.'
  else
    local output
    output="$("$NODE" "$tool" "$service" create)" || fail 'TLS certificate installation failed.'
    [[ "$output" =~ ^$service\ fingerprint:\ sha256/[A-Za-z0-9+/]{43}=$ ]] || fail 'TLS tool did not confirm a fingerprint; refusing to continue.'
    printf '%s\n' "$output"
  fi
}
